CREATE TABLE client
(id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR NOT NULL CHECK(CHAR_LENGTH(name)<=200 AND CHAR_LENGTH(name)>=3));

CREATE TABLE planet
(id VARCHAR PRIMARY KEY Constraint id CHECK (id = UPPER(id)),
name VARCHAR NOT NULL CHECK(CHAR_LENGTH(name)<=500 AND CHAR_LENGTH(name)>=1));

CREATE TABLE ticket
(id INT PRIMARY KEY AUTO_INCREMENT,
created_at TIMESTAMP WITH TIME ZONE,
client_id  INT,
from_planet_id VARCHAR,
to_planet_id  VARCHAR,
FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE,
FOREIGN KEY (from_planet_id) REFERENCES planet (id) ON DELETE CASCADE,
FOREIGN KEY (to_planet_id) REFERENCES planet (id) ON DELETE CASCADE
);